### ISSUE TITLE
Version management: update dependencies to new style in config.yml and other files: definition.yml

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#164]
SemVer is the way to go.

old style
```yaml
load-order:
- a == 0.1.0
- b ^0.2.0
```

new style
```yaml
load-order:
- a: "= 0.1.0"
- b: "^0.2.0"
```
