### ISSUE TITLE
Implement priority-ordered-set

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#217]
Two use cases: maploader & balance module

Could look like this::
```yml
url: feature.with.an.array.of.paths
contents:
  type: priority-ordered-set # Add paths defined by extensions in the same order as the priority of extensions, no duplicates
  type-element: string
  value: []
```
