### ISSUE TITLE
[CONTENT] Create collapsible families of extensions

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#274]
**Proposal**
Modify definition.yml to include a `family:` field that can list the family of extensions it belongs to. This way, we can collapse extensions of the same family into one display node. The family needs to define a `root` extension that will be the one for display purposes. And if nothing is uncollapsed then this root is activated upon click.

Root extension:
```yml
name: extension-A
version: B
family:
- name: extension-A-family
  root: true
```

Family extension:
```yml
name: extension-A-files
version: B
family:
- name: extension-A-family
```
