### ISSUE TITLE
ui.yml: decide on specification of value

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#7]
```yml
- type: number
  value:
    default: 0
    min: 1
    max: 10
``` 

instead of

```yml
- type: number
  value:
    default: 0
  min: 1
  max: 10
```
